name: Generate Insights

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  generate-insights:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: insights
          fetch-depth: 0

      - name: Ensure 'insights' branch exists
        run: |
          git fetch origin insights || echo "No 'insights' branch found"
          git checkout insights || git checkout -b insights

      - name: Generate GitHub Insights
        uses: emillig/github-repo-insights@main
        with:
          repos: "MYNAMMEJACK/foodorder,MYNAMMEJACK/gogo,MYNAMMEJACK/cv-website"
          pat-token: ${{ secrets.PAT_TOKEN }}

      - name: Commit and push insights
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update GitHub Insights" || echo "No changes to commit"
          git push origin insights
